In [2]:
import numpy as np

There are a couple of ways to create an array, lets say, you have a python list and you want to create an array

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

You can cast this list into an array, like this:

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
# np.array returns an array object, store it in myarray
myarray = np.array(mylist)

In [7]:
#check the type of myarray
type(myarray)

numpy.ndarray

## Topic 1: Creating arrays
You can have 2d array, 3d array etc. Here are some methods of creating arrays:
- np.arange - you can create an array by giving start, stop and step values.

### np.arange()

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# another example
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### np.zeros() and np.ones()
Create a 2/3 dimensional array all with same value.

In [10]:
np.zeros(shape=(5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Topic 2: Use of seed
What this does is that, it allows us to create the same random numbers each time. We are doing this because, we want to have some random numbers for the next set of operations.

In [12]:
# to create a seed
np.random.seed(101)

In [13]:
arr = np.random.randint(0, 100, 10)

In [14]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [15]:
arr2 = np.random.randint(0, 100, 10)

In [16]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

## Finding the max/min/mean of an array

In [17]:
# to find the max value use max
arr.max()

95

In [18]:
# to find the location of the max value use argmax
arr.argmax()

0

## Reshape arrays

In [19]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

## Indexing arrays

In [20]:
# lets first create a matrix
mat = np.random.randint(0, 100, 100).reshape(10,10)

In [21]:
mat

array([[49, 83,  8, 29, 59, 34, 44, 72, 19, 10],
       [76, 95, 87,  0, 73,  8, 62, 36, 83, 99],
       [28, 63,  7, 10, 52, 56, 38, 73, 52, 18],
       [71, 15, 44,  0, 12, 17, 75, 79, 97, 93],
       [24, 36, 63, 19, 35, 30, 10, 60, 20, 27],
       [ 8, 86, 26, 87, 46, 47, 54, 86,  9, 45],
       [ 2, 18, 58, 92, 11, 10, 94, 35, 28,  3],
       [83, 84, 47, 14, 69, 60, 69, 51,  6, 88],
       [71, 68, 23, 35, 79, 98, 67, 82, 57, 77],
       [46,  3, 46, 29, 86, 21, 21, 81, 23, 94]])